# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{ system ? builtins.currentSystem, pkgs, lib, fetchurl, installShellFiles }:
let
  shaMap = {
    i686-linux = "1f0y6lz0gck49zikh83w9sar9spj75kd2585zakmh2yfl8cn1qfv";
    x86_64-linux = "0b44x065a6a32z70bfskyw56hxnfvr4j1aj1zsparm4wvgr3iy56";
    armv7l-linux = "023ilc692n6x7b72640nl34ssrjn3cdckk7a65iksywy5bl4grxa";
    aarch64-linux = "0g40gy46xyvhvv0r19z22fkiq1a0px4b1c8cj0nj0az3fa3ihyxb";
    x86_64-darwin = "1xrpm9bn5l03xmn60xj95igvx62ahkgsmm10ab87jwp9x02f8w2q";
    aarch64-darwin = "1xnqbvhq9rlicmcb3zy131cja5rhrcmk4qs6rv6b9v4p81adzh6n";
  };

  urlMap = {
    i686-linux = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.0/goreleaser_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.0/goreleaser_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.0/goreleaser_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.0/goreleaser_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.0/goreleaser_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.0/goreleaser_Darwin_arm64.tar.gz";
  };
in pkgs.stdenv.mkDerivation {
  pname = "goreleaser";
  version = "1.19.0";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./goreleaser $out/bin/goreleaser
    installManPage ./manpages/goreleaser.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = with lib; {
    description = "Deliver Go binaries as fast and easily as possible";
    homepage = "https://goreleaser.com";
    license = licenses.mit;

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
