# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{ system ? builtins.currentSystem, pkgs, lib, fetchurl, installShellFiles }:
let
  shaMap = {
    i686-linux = "1djqa4zzwfksfimvl3qar6cbpg67fq7jm5pqqd40m4ghj6xv2axc";
    x86_64-linux = "07nsi92hjpc8iv5v4a3zhpxjky9xxjpcbk6bi27hjhvch5xkkir7";
    armv7l-linux = "0mbn0gwdbwxjklbsh7nif3sh3wd8hkvkl3rxhfkwgm2zfmm0iln3";
    aarch64-linux = "1aq0j01wcv1rnwjnrbn9x9cf8v4bffdvlw4v17xa56426yr5a8x5";
    x86_64-darwin = "0ckhrnljjqxs7syyij2yx63whvlccnf4mhiv4a5qwvh23ajg98ln";
    aarch64-darwin = "1j8wyisbqzvzcw8zs5pb24y0hhif1r7c1ifiaf7wh1hfi4dgyjvn";
  };

  urlMap = {
    i686-linux = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.2/goreleaser_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.2/goreleaser_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.2/goreleaser_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.2/goreleaser_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.2/goreleaser_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/goreleaser/goreleaser/releases/download/v1.19.2/goreleaser_Darwin_arm64.tar.gz";
  };
in pkgs.stdenv.mkDerivation {
  pname = "goreleaser";
  version = "1.19.2";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./goreleaser $out/bin/goreleaser
    installManPage ./manpages/goreleaser.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = with lib; {
    description = "Deliver Go binaries as fast and easily as possible";
    homepage = "https://goreleaser.com";
    license = licenses.mit;

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
