# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, lib
, fetchurl
, installShellFiles
, stdenvNoCC
}:
let
  shaMap = {
    i686-linux = "06rdinz6zcw7641v0apqlgzbrhq0h6v75xwwb9pli7scgimzsbl1";
    x86_64-linux = "0802lzi5mr9y6cpszjg0mvbhkgryjvf8r06cz4fc5k3pcwr53pkf";
    armv7l-linux = "0jdqak8rhk5dwlmynx7qgrymc6apx7kxklv2rvi2fqc78yy0i99c";
    aarch64-linux = "1ahim3c0313c3wifprp6nc3pq32b1vmm2imxqlpydrzfxwymvpzl";
    x86_64-darwin = "0d3r5rcw5g10ph8fcdg0klm8ng9p4xqv7z812fz7qzbzfd88hp64";
    aarch64-darwin = "12zjw0xlccqbb4k38559994icvg5zrjyagdqa1rr2vvpcd4pz1zb";
  };

  urlMap = {
    i686-linux = "https://github.com/goreleaser/goreleaser/releases/download/v2.12.4/goreleaser_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/goreleaser/goreleaser/releases/download/v2.12.4/goreleaser_Linux_x86_64.tar.gz";
    armv7l-linux = "https://github.com/goreleaser/goreleaser/releases/download/v2.12.4/goreleaser_Linux_armv7.tar.gz";
    aarch64-linux = "https://github.com/goreleaser/goreleaser/releases/download/v2.12.4/goreleaser_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/goreleaser/goreleaser/releases/download/v2.12.4/goreleaser_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/goreleaser/goreleaser/releases/download/v2.12.4/goreleaser_Darwin_arm64.tar.gz";
  };
in
stdenvNoCC.mkDerivation {
  pname = "goreleaser";
  version = "2.12.4";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    cp -vr ./goreleaser $out/bin/goreleaser
    installManPage ./manpages/goreleaser.1.gz
    installShellCompletion ./completions/*
  '';

  system = system;

  meta = {
    description = "Release engineering, simplified";
    homepage = "https://goreleaser.com";
    license = lib.licenses.mit;

    sourceProvenance = [ lib.sourceTypes.binaryNativeCode ];

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "armv7l-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
